replicaCount: 1

image:
  repository: celery-redis-app_v7 #Celery_image
  pullPolicy: IfNotPresent
  tag: "latest"
  
app:
  name: celery-app

service:
  type: ClusterIP
  port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
