apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe: # checks if application is running
          httpGet:
            path: /healthz  # endpoint
            port: {{ .Values.service.port }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe: # check if container should start receiving traffic
          httpGet:
            path: /ready  # readiness check endpoint
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
